//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigSister.RScript {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:RScriptLookup", ConfigurationName="RScript.RScriptLookupPortType")]
    public interface RScriptLookupPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:RScriptLookup#stats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BigSister.RScript.skills stats(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:RScriptLookup#trackGetTimeAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BigSister.RScript.skills trackGetTimeAll(string name, int time);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:RScriptLookup#trackGetAgoAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BigSister.RScript.skills trackGetTimeAgoAll(string name, int time);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:RScriptLookup#trackUpdateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool trackUpdateUser(string name);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:RScriptLookup")]
    public partial class skills : object, System.ComponentModel.INotifyPropertyChanged {
        
        private skillVar overallField;
        
        private skillVar attackField;
        
        private skillVar defenceField;
        
        private skillVar strengthField;
        
        private skillVar hitpointsField;
        
        private skillVar rangedField;
        
        private skillVar prayerField;
        
        private skillVar magicField;
        
        private skillVar cookingField;
        
        private skillVar woodcuttingField;
        
        private skillVar fletchingField;
        
        private skillVar fishingField;
        
        private skillVar firemakingField;
        
        private skillVar craftingField;
        
        private skillVar smithingField;
        
        private skillVar miningField;
        
        private skillVar herbloreField;
        
        private skillVar agilityField;
        
        private skillVar thievingField;
        
        private skillVar slayerField;
        
        private skillVar farmingField;
        
        private skillVar runecraftField;
        
        private skillVar hunterField;
        
        private skillVar constructionField;
        
        private skillVar summoningField;
        
        /// <remarks/>
        public skillVar overall {
            get {
                return this.overallField;
            }
            set {
                this.overallField = value;
                this.RaisePropertyChanged("overall");
            }
        }
        
        /// <remarks/>
        public skillVar attack {
            get {
                return this.attackField;
            }
            set {
                this.attackField = value;
                this.RaisePropertyChanged("attack");
            }
        }
        
        /// <remarks/>
        public skillVar defence {
            get {
                return this.defenceField;
            }
            set {
                this.defenceField = value;
                this.RaisePropertyChanged("defence");
            }
        }
        
        /// <remarks/>
        public skillVar strength {
            get {
                return this.strengthField;
            }
            set {
                this.strengthField = value;
                this.RaisePropertyChanged("strength");
            }
        }
        
        /// <remarks/>
        public skillVar hitpoints {
            get {
                return this.hitpointsField;
            }
            set {
                this.hitpointsField = value;
                this.RaisePropertyChanged("hitpoints");
            }
        }
        
        /// <remarks/>
        public skillVar ranged {
            get {
                return this.rangedField;
            }
            set {
                this.rangedField = value;
                this.RaisePropertyChanged("ranged");
            }
        }
        
        /// <remarks/>
        public skillVar prayer {
            get {
                return this.prayerField;
            }
            set {
                this.prayerField = value;
                this.RaisePropertyChanged("prayer");
            }
        }
        
        /// <remarks/>
        public skillVar magic {
            get {
                return this.magicField;
            }
            set {
                this.magicField = value;
                this.RaisePropertyChanged("magic");
            }
        }
        
        /// <remarks/>
        public skillVar cooking {
            get {
                return this.cookingField;
            }
            set {
                this.cookingField = value;
                this.RaisePropertyChanged("cooking");
            }
        }
        
        /// <remarks/>
        public skillVar woodcutting {
            get {
                return this.woodcuttingField;
            }
            set {
                this.woodcuttingField = value;
                this.RaisePropertyChanged("woodcutting");
            }
        }
        
        /// <remarks/>
        public skillVar fletching {
            get {
                return this.fletchingField;
            }
            set {
                this.fletchingField = value;
                this.RaisePropertyChanged("fletching");
            }
        }
        
        /// <remarks/>
        public skillVar fishing {
            get {
                return this.fishingField;
            }
            set {
                this.fishingField = value;
                this.RaisePropertyChanged("fishing");
            }
        }
        
        /// <remarks/>
        public skillVar firemaking {
            get {
                return this.firemakingField;
            }
            set {
                this.firemakingField = value;
                this.RaisePropertyChanged("firemaking");
            }
        }
        
        /// <remarks/>
        public skillVar crafting {
            get {
                return this.craftingField;
            }
            set {
                this.craftingField = value;
                this.RaisePropertyChanged("crafting");
            }
        }
        
        /// <remarks/>
        public skillVar smithing {
            get {
                return this.smithingField;
            }
            set {
                this.smithingField = value;
                this.RaisePropertyChanged("smithing");
            }
        }
        
        /// <remarks/>
        public skillVar mining {
            get {
                return this.miningField;
            }
            set {
                this.miningField = value;
                this.RaisePropertyChanged("mining");
            }
        }
        
        /// <remarks/>
        public skillVar herblore {
            get {
                return this.herbloreField;
            }
            set {
                this.herbloreField = value;
                this.RaisePropertyChanged("herblore");
            }
        }
        
        /// <remarks/>
        public skillVar agility {
            get {
                return this.agilityField;
            }
            set {
                this.agilityField = value;
                this.RaisePropertyChanged("agility");
            }
        }
        
        /// <remarks/>
        public skillVar thieving {
            get {
                return this.thievingField;
            }
            set {
                this.thievingField = value;
                this.RaisePropertyChanged("thieving");
            }
        }
        
        /// <remarks/>
        public skillVar slayer {
            get {
                return this.slayerField;
            }
            set {
                this.slayerField = value;
                this.RaisePropertyChanged("slayer");
            }
        }
        
        /// <remarks/>
        public skillVar farming {
            get {
                return this.farmingField;
            }
            set {
                this.farmingField = value;
                this.RaisePropertyChanged("farming");
            }
        }
        
        /// <remarks/>
        public skillVar runecraft {
            get {
                return this.runecraftField;
            }
            set {
                this.runecraftField = value;
                this.RaisePropertyChanged("runecraft");
            }
        }
        
        /// <remarks/>
        public skillVar hunter {
            get {
                return this.hunterField;
            }
            set {
                this.hunterField = value;
                this.RaisePropertyChanged("hunter");
            }
        }
        
        /// <remarks/>
        public skillVar construction {
            get {
                return this.constructionField;
            }
            set {
                this.constructionField = value;
                this.RaisePropertyChanged("construction");
            }
        }
        
        /// <remarks/>
        public skillVar summoning {
            get {
                return this.summoningField;
            }
            set {
                this.summoningField = value;
                this.RaisePropertyChanged("summoning");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:RScriptLookup")]
    public partial class skillVar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int rankField;
        
        private int expField;
        
        private int levelField;
        
        /// <remarks/>
        public int rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("rank");
            }
        }
        
        /// <remarks/>
        public int exp {
            get {
                return this.expField;
            }
            set {
                this.expField = value;
                this.RaisePropertyChanged("exp");
            }
        }
        
        /// <remarks/>
        public int level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("level");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface RScriptLookupPortTypeChannel : BigSister.RScript.RScriptLookupPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RScriptLookupPortTypeClient : System.ServiceModel.ClientBase<BigSister.RScript.RScriptLookupPortType>, BigSister.RScript.RScriptLookupPortType {
        
        public RScriptLookupPortTypeClient() {
        }
        
        public RScriptLookupPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RScriptLookupPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RScriptLookupPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RScriptLookupPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BigSister.RScript.skills stats(string name) {
            return base.Channel.stats(name);
        }
        
        public BigSister.RScript.skills trackGetTimeAll(string name, int time) {
            return base.Channel.trackGetTimeAll(name, time);
        }
        
        public BigSister.RScript.skills trackGetTimeAgoAll(string name, int time) {
            return base.Channel.trackGetTimeAgoAll(name, time);
        }
        
        public bool trackUpdateUser(string name) {
            return base.Channel.trackUpdateUser(name);
        }
    }
}
